=== ROBERTOCABALLEROCUBERO/Examen3EvLM/XML/tiempo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="https://www.w3schools.com" xmlns="https://www.w3schools.com" elementFormDefault="qualified">
    <xs:element name="info_meteo">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Comunidades_Autonomas" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType >
                        <xs:sequence>
                           <xs:element name="provincias" minOccurs="1" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Poblacion" minOccurs="1" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="prediccion" minOccurs="1" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="Fecha" type="xs:date"></xs:element>
                                                                <xs:element name="Temperatura_maxima" type="xs:decimal"></xs:element>
                                                                <xs:element name="Temperatura_minima" type="xs:decimal"></xs:element>
                                                                <xs:element name="Prob_Lluvia" type="xs:decimal"></xs:element>
                                                                <xs:element name="Avisos_riesgo"></xs:element>
                                                            </xs:sequence>
                                                           
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="nombre" use="required" type="xs:string"></xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="nombre" use="required" type="xs:string"></xs:attribute>
                                </xs:complexType>
                            </xs:element>                    
                        </xs:sequence>
                        <xs:attribute name="nombre" use="required" type="xs:string"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="nombre" use="required" type="xs:string"></xs:attribute>
        </xs:complexType>
    </xs:element>


</xs:schema>

=== ROBERTOCABALLEROCUBERO/Examen3EvLM/XML/tiempo_nacional.xml
<?xml version="1.0" encoding="UTF-8"?>
<info_meteo  xmlns="https://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="tiempo.xsd">
    <Comunidades_Autonomas nombre = "Madrid">
        <provincias nombre = "Madrid">
            <Poblacion nombre = "Alcobendas">
                <prediccion>
                    <fecha></fecha>
                    <Temperatura_maxima></Temperatura_maxima>
                    <Temperatura_minima></Temperatura_minima>
                    <Prob_Lluvia></Prob_Lluvia>
                    <Avisos_riesgo></Avisos_riesgo>
                </prediccion>
            </Poblacion>
        </provincias>

    </Comunidades_Autonomas>


</info_meteo>
